name: saltstack-libvirt-formula
source: https://github.com/bechtoldt/saltstack-libvirt-formula
summary: SaltStack Formula to set up and configure libvirt, a virtualization API
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - Manage libvirt/ KVM/ QEMU configuration files
extra:
  asciinema:
    link: https://asciinema.org/a/38jyzix32bngnvm4ei1k7jzva
